services:
  web:
    build: ./web
    command: python manage.py runserver 0.0.0.0:8000
    container_name: web
    ports:
      - "8000:8000"
    volumes:
      - ./web:/app
    environment:
      SECRET_KEY: "django-insecure-7868768768776gr6rcv7r76c5676f576f5"
      ALLOWED_HOSTS: "*"
      HTTP_HOST_CANONICAL: "localhost"
      BASE_URL: "localhost:8001"
      DATABASE_URL: "postgres://postgres:password@db:5432/postgres"
      DEBUG: 1
      VERSION: "dev"
    depends_on:
      - db
  db:
    image: postgres:16-alpine
    container_name: db
#    ports:
#      - "5432:5432"
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: "password"
      LANG: "en_US.UTF-8"
      LC_COLLATE: "en_US.UTF-8"
      LC_CTYPE: "en_US.UTF-8"
volumes:
  postgres_volume:
    name: projekt_postgres_volume
